apiVersion: v1
kind: PersistentVolume
metadata:
  name: devconf-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/app
  persistentVolumeReclaimPolicy: Delete
