apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devconf-pvc-1
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  storageClassName: standard
  volumeName: devconf-pv-1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devconf-pvc-2
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  storageClassName: standard
  volumeName: devconf-pv-2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
