apiVersion: v1
kind: ServiceAccount
metadata:
  name: devconf-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devconf-role
rules:
  - apiGroups: [""]
    resources: ["deployment","services","pvc","job"]
    verbs: ["create","get","list","delete","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments","services","pvc","job"]
    verbs: ["create","get","list","delete","patch"]
  - apiGroups: ["v1"]
    resources: ["deployment","services","pvc","job"]
    verbs: ["create","get","list","delete","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devconf-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devconf-role
subjects:
- kind: ServiceAccount
  name: devconf-sa
---
