apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: devconf-ahub-hub-
spec:
  taskRunTemplate:
    serviceAccountName: devconf-sa
  pipelineRef:
    name: artifact-pipeline
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: devconf-pvc-2
  params:
    - name: GIT_URL
      value: https://github.com/CodeRepOrg/test-repo.git

