apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: artifact-pipeline
spec:
  workspaces:
    - name: shared-data
  params:
    - name: GIT_URL
      type: string
      description: Url of the repo
      default: https://github.com/CodeRepOrg/test-repo.git
    - name: YAML_PATH
      type: string
      description: Path to yaml file
      default: kubernetes/deployment.yaml
  tasks:
    - name: clone
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.5.0"
      params:
        - name: url
          value: $(params.GIT_URL)
      workspaces:
        - name: output
          workspace: shared-data
          
    # - name: build
    #   runAfter:
    #     - clone
    #   taskRef:
    #     name: buildah-personal
    #   params:
    #     - name: IMAGE
    #       value: docker.io/joaopedropp/devconf-ahub
    #   workspaces:
    #     - name: output
    #       workspace: shared-data

    - name: build
      runAfter:
        - clone
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/CodeRepOrg/tkn-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: artifact-hub/buildah.yaml
      params:
        - name: IMAGE
          value: docker.io/joaopedropp/devconf-ahub
      workspaces:
        - name: output
          workspace: shared-data

    - name: deploy
      runAfter:
        - build
      taskSpec:
        steps:
          - image: alpine
            name: update-yaml
            workingDir: $(workspaces.output.path)
            command:
              - "sed"
            args:
              - "-i"
              - "-e"
              - "s;__IMAGE__;docker.io/joaopedropp/devconf-ahub:latest;g"
              - "$(params.YAML_PATH)"
          - image: bitnami/kubectl
            name: k8
            workingDir: $(workspaces.output.path)
            command:
              - kubectl
            args:
              - apply
              - "-f"
              - "$(params.YAML_PATH)"
      workspaces:
        - name: output
          workspace: shared-data
